name: Automated Testing

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  code-hygiene:
    name: Code Hygiene
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false }
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run lint
        if: success() || failure()
      - run: npm run typecheck
        if: success() || failure()
  unit-and-integration-tests:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false }
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run test-unit-ci
      - run: npm run test-integration-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ${{ github.workspace }}/coverage/vitest/unit/coverage-final.json, ${{ github.workspace }}/coverage/vitest/integration/coverage-final.json
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  packaging-tests:
    name: Packaging and Build tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false }
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run generate-style-spec
      - run: npm run generate-typings
      - run: npm run build
      - run: npm run test-build-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ${{ github.workspace }}/coverage/vitest/build/coverage-final.json
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
