name: Automated Testing

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  code-hygiene:
    name: Code Hygiene
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: { persist-credentials: false }
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run lint
        if: success() || failure()
      - run: npm run typecheck
        if: success() || failure()
  unit-and-integration-tests:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: { persist-credentials: false }
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run test-unit-ci
      - run: npm run test-integration-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: ${{ github.workspace }}/coverage/vitest/unit/coverage-final.json, ${{ github.workspace }}/coverage/vitest/integration/coverage-final.json
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          
  packaging-tests:
    name: Packaging and Build tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: { persist-credentials: false }
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run generate-style-spec
      - run: npm run generate-typings
      - run: npm run build
      - run: npm run test-build-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: ${{ github.workspace }}/coverage/vitest/build/coverage-final.json
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
